// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "ImGuizmo.h"

#include <stdio.h>

// Wrap this in a namespace to keep it separate from the C++ API.
#define DEAR_BINDINGS_INTERNAL_GLUE_CODE
namespace cimgui
{
#include "cimguizmo.h"
}
#undef DEAR_BINDINGS_INTERNAL_GLUE_CODE
// By-value struct conversions

static inline cimgui::ImVec2 ConvertFromCPP_ImVec2(const ::ImVec2& src)
{
    cimgui::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline ::ImVec2 ConvertToCPP_ImVec2(const cimgui::ImVec2& src)
{
    ::ImVec2 dest;
    dest.x = src.x;
    dest.y = src.y;
    return dest;
}

static inline cimgui::ImVec4 ConvertFromCPP_ImVec4(const ::ImVec4& src)
{
    cimgui::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline ::ImVec4 ConvertToCPP_ImVec4(const cimgui::ImVec4& src)
{
    ::ImVec4 dest;
    dest.x = src.x;
    dest.y = src.y;
    dest.z = src.z;
    dest.w = src.w;
    return dest;
}

static inline cimgui::ImTextureRef ConvertFromCPP_ImTextureRef(const ::ImTextureRef& src)
{
    cimgui::ImTextureRef dest;
    dest._TexData = reinterpret_cast<cimgui::ImTextureData*>(src._TexData);
    dest._TexID = src._TexID;
    return dest;
}

static inline ::ImTextureRef ConvertToCPP_ImTextureRef(const cimgui::ImTextureRef& src)
{
    ::ImTextureRef dest;
    dest._TexData = reinterpret_cast<::ImTextureData*>(src._TexData);
    dest._TexID = src._TexID;
    return dest;
}

static inline cimgui::ImColor ConvertFromCPP_ImColor(const ::ImColor& src)
{
    cimgui::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

static inline ::ImColor ConvertToCPP_ImColor(const cimgui::ImColor& src)
{
    ::ImColor dest;
    dest.Value.x = src.Value.x;
    dest.Value.y = src.Value.y;
    dest.Value.z = src.Value.z;
    dest.Value.w = src.Value.w;
    return dest;
}

// Function stubs

#if 0

CIMGUI_API void cimgui::cEditTransform(Camera camera, matrix_t* matrix)
{
    ::EditTransform(reinterpret_cast<const ::Camera&>(camera), *matrix);
}

#endif // #if 0

CIMGUI_API void cimgui::ImGuizmoSetDrawlist(void)
{
    ::ImGuizmo::SetDrawlist();
}

CIMGUI_API void cimgui::ImGuizmoSetDrawlistEx(cimgui::ImDrawList* drawlist)
{
    ::ImGuizmo::SetDrawlist(reinterpret_cast<::ImDrawList*>(drawlist));
}

CIMGUI_API void cimgui::ImGuizmoBeginFrame(void)
{
    ::ImGuizmo::BeginFrame();
}

CIMGUI_API void cimgui::ImGuizmoSetImGuiContext(cimgui::ImGuiContext* ctx)
{
    ::ImGuizmo::SetImGuiContext(reinterpret_cast<::ImGuiContext*>(ctx));
}

CIMGUI_API bool cimgui::ImGuizmoIsOver(void)
{
    return ::ImGuizmo::IsOver();
}

CIMGUI_API bool cimgui::ImGuizmoIsUsing(void)
{
    return ::ImGuizmo::IsUsing();
}

CIMGUI_API bool cimgui::ImGuizmoIsUsingViewManipulate(void)
{
    return ::ImGuizmo::IsUsingViewManipulate();
}

CIMGUI_API bool cimgui::ImGuizmoIsViewManipulateHovered(void)
{
    return ::ImGuizmo::IsViewManipulateHovered();
}

CIMGUI_API bool cimgui::ImGuizmoIsUsingAny(void)
{
    return ::ImGuizmo::IsUsingAny();
}

CIMGUI_API void cimgui::ImGuizmoEnable(bool enable)
{
    ::ImGuizmo::Enable(enable);
}

CIMGUI_API void cimgui::ImGuizmoDecomposeMatrixToComponents(const float* matrix, float* translation, float* rotation, float* scale)
{
    ::ImGuizmo::DecomposeMatrixToComponents(matrix, translation, rotation, scale);
}

CIMGUI_API void cimgui::ImGuizmoRecomposeMatrixFromComponents(const float* translation, const float* rotation, const float* scale, float* matrix)
{
    ::ImGuizmo::RecomposeMatrixFromComponents(translation, rotation, scale, matrix);
}

CIMGUI_API void cimgui::ImGuizmoSetRect(float x, float y, float width, float height)
{
    ::ImGuizmo::SetRect(x, y, width, height);
}

CIMGUI_API void cimgui::ImGuizmoSetOrthographic(bool isOrthographic)
{
    ::ImGuizmo::SetOrthographic(isOrthographic);
}

CIMGUI_API void cimgui::ImGuizmoDrawAxes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGuizmo::DrawAxes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmoDrawCubes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGuizmo::DrawCubes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmoDrawGrid(const float* view, const float* projection, const float* matrix, const float gridSize)
{
    ::ImGuizmo::DrawGrid(view, projection, matrix, gridSize);
}

CIMGUI_API void cimgui::ImGuizmoDrawGridCustom(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision)
{
    ::ImGuizmo::DrawGridCustom(view, projection, matrix, gridSize, majorStep, subdivision);
}

CIMGUI_API void cimgui::ImGuizmoDrawGridCustomColor(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision, const ImU32 majorCol, const ImU32 minorCol, const ImU32 centerCol)
{
    ::ImGuizmo::DrawGridCustomColor(view, projection, matrix, gridSize, majorStep, subdivision, majorCol, minorCol, centerCol);
}

CIMGUI_API bool cimgui::ImGuizmoManipulate(const float* view, const float* projection, cimgui::ImGuizmoOPERATION operation, cimgui::ImGuizmoMODE mode, float* matrix)
{
    return ::ImGuizmo::Manipulate(view, projection, static_cast<::ImGuizmo::OPERATION>(operation), static_cast<::ImGuizmo::MODE>(mode), matrix);
}

CIMGUI_API bool cimgui::ImGuizmoManipulateEx(const float* view, const float* projection, cimgui::ImGuizmoOPERATION operation, cimgui::ImGuizmoMODE mode, float* matrix, float* deltaMatrix, const float* snap, const float* localBounds, const float* boundsSnap)
{
    return ::ImGuizmo::Manipulate(view, projection, static_cast<::ImGuizmo::OPERATION>(operation), static_cast<::ImGuizmo::MODE>(mode), matrix, deltaMatrix, snap, localBounds, boundsSnap);
}

CIMGUI_API void cimgui::ImGuizmoViewManipulate(float* view, float length, cimgui::ImVec2 position, cimgui::ImVec2 size, ImU32 backgroundColor)
{
    ::ImGuizmo::ViewManipulate(view, length, ConvertToCPP_ImVec2(position), ConvertToCPP_ImVec2(size), backgroundColor);
}

CIMGUI_API void cimgui::ImGuizmoViewManipulateFloatPtr(float* view, const float* projection, cimgui::ImGuizmoOPERATION operation, cimgui::ImGuizmoMODE mode, float* matrix, float length, cimgui::ImVec2 position, cimgui::ImVec2 size, ImU32 backgroundColor)
{
    ::ImGuizmo::ViewManipulate(view, projection, static_cast<::ImGuizmo::OPERATION>(operation), static_cast<::ImGuizmo::MODE>(mode), matrix, length, ConvertToCPP_ImVec2(position), ConvertToCPP_ImVec2(size), backgroundColor);
}

CIMGUI_API void cimgui::ImGuizmoSetAlternativeWindow(cimgui::ImGuiWindow* window)
{
    ::ImGuizmo::SetAlternativeWindow(reinterpret_cast<::ImGuiWindow*>(window));
}

CIMGUI_API void cimgui::ImGuizmoSetID(int id)
{
    ::ImGuizmo::SetID(id);
}

CIMGUI_API void    cimgui::ImGuizmoPushID(const char* str_id)
{
    ::ImGuizmo::PushID(str_id);
}

CIMGUI_API void    cimgui::ImGuizmoPushIDStr(const char* str_id_begin, const char* str_id_end)
{
    ::ImGuizmo::PushID(str_id_begin, str_id_end);
}

CIMGUI_API void    cimgui::ImGuizmoPushIDPtr(const void* ptr_id)
{
    ::ImGuizmo::PushID(ptr_id);
}

CIMGUI_API void    cimgui::ImGuizmoPushIDInt(int int_id)
{
    ::ImGuizmo::PushID(int_id);
}

CIMGUI_API void    cimgui::ImGuizmoPopID(void)
{
    ::ImGuizmo::PopID();
}

CIMGUI_API ImGuiID cimgui::ImGuizmoGetID(const char* str_id)
{
    return ::ImGuizmo::GetID(str_id);
}

CIMGUI_API ImGuiID cimgui::ImGuizmoGetIDStr(const char* str_id_begin, const char* str_id_end)
{
    return ::ImGuizmo::GetID(str_id_begin, str_id_end);
}

CIMGUI_API ImGuiID cimgui::ImGuizmoGetIDPtr(const void* ptr_id)
{
    return ::ImGuizmo::GetID(ptr_id);
}

CIMGUI_API bool cimgui::ImGuizmoIsOverOPERATION(cimgui::ImGuizmoOPERATION op)
{
    return ::ImGuizmo::IsOver(static_cast<::ImGuizmo::OPERATION>(op));
}

CIMGUI_API void cimgui::ImGuizmoSetGizmoSizeClipSpace(float value)
{
    ::ImGuizmo::SetGizmoSizeClipSpace(value);
}

CIMGUI_API cimgui::ImGuizmoMOVETYPE cimgui::ImGuizmoGetActiveHandleType(void)
{
    return static_cast<::cimgui::ImGuizmoMOVETYPE>(::ImGuizmo::GetActiveHandleType());
}

CIMGUI_API cimgui::ImGuizmoMOVETYPE cimgui::ImGuizmoGetHoveredHandleType(void)
{
    return static_cast<::cimgui::ImGuizmoMOVETYPE>(::ImGuizmo::GetHoveredHandleType());
}

CIMGUI_API cimgui::ImGuizmoMOVETYPE cimgui::ImGuizmoGetActiveMoveType(void)
{
    return static_cast<::cimgui::ImGuizmoMOVETYPE>(::ImGuizmo::GetActiveMoveType());
}

CIMGUI_API cimgui::ImGuizmoMOVETYPE cimgui::ImGuizmoGetHoveredMoveType(void)
{
    return static_cast<::cimgui::ImGuizmoMOVETYPE>(::ImGuizmo::GetHoveredMoveType());
}

CIMGUI_API void cimgui::ImGuizmoAllowAxisFlip(bool value)
{
    ::ImGuizmo::AllowAxisFlip(value);
}

CIMGUI_API void cimgui::ImGuizmoSetAxisLimit(float value)
{
    ::ImGuizmo::SetAxisLimit(value);
}

CIMGUI_API void cimgui::ImGuizmoSetAxisMask(bool x, bool y, bool z)
{
    ::ImGuizmo::SetAxisMask(x, y, z);
}

CIMGUI_API void cimgui::ImGuizmoSetPlaneLimit(float value)
{
    ::ImGuizmo::SetPlaneLimit(value);
}

CIMGUI_API bool cimgui::ImGuizmoIsOverFloatPtr(float* position, float pixelRadius)
{
    return ::ImGuizmo::IsOver(position, pixelRadius);
}

CIMGUI_API cimgui::ImGuizmoStyle* cimgui::ImGuizmoGetStyle(void)
{
    return reinterpret_cast<::cimgui::ImGuizmoStyle*>(&::ImGuizmo::GetStyle());
}
