// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "ImGuizmo.h"

#include <stdio.h>

typedef ImGuizmo::OPERATION OPERATION;
typedef ImGuizmo::MODE MODE;
typedef ImGuizmo::MOVETYPE MOVETYPE;
typedef ImGuizmo::COLOR COLOR;
typedef ImGuizmo::Style Style;

// Define the typedefs in the global namespace and guard them
// so they are available globally for return types in cimguizmo.cpp,
// and the duplicate definitions in cimguizmo.h are skipped.
typedef ::OPERATION ImGuizmo_OPERATION;
#define ImGuizmo_OPERATION_DEFINED

typedef ::MODE ImGuizmo_MODE;
#define ImGuizmo_MODE_DEFINED

typedef ::MOVETYPE ImGuizmo_MOVETYPE;
#define ImGuizmo_MOVETYPE_DEFINED

typedef ::COLOR ImGuizmo_COLOR;
#define ImGuizmo_COLOR_DEFINED

typedef ::Style ImGuizmo_Style;
#define ImGuizmo_Style_DEFINED

// Wrap this in a namespace to keep it separate from the C++ API.
#define DEAR_BINDINGS_INTERNAL_GLUE_CODE
namespace cimgui
{
    typedef ::OPERATION OPERATION;
    typedef ::MODE MODE;
    typedef ::MOVETYPE MOVETYPE;
    typedef ::COLOR COLOR;
    typedef ::Style Style;

    #include "cimguizmo.h"
}
#undef DEAR_BINDINGS_INTERNAL_GLUE_CODE
// By-value struct conversions

// Function stubs

#if 0

CIMGUI_API void cimgui::cEditTransform(Camera camera, matrix_t* matrix)
{
    ::EditTransform(reinterpret_cast<const ::Camera&>(camera), *matrix);
}

#endif // #if 0

CIMGUI_API void cimgui::ImGuizmo_SetDrawlist(void)
{
    ::ImGui::SetDrawlist();
}

CIMGUI_API void cimgui::ImGuizmo_SetDrawlistEx(ImDrawList* drawlist)
{
    ::ImGui::SetDrawlist(drawlist);
}

CIMGUI_API void cimgui::ImGuizmo_BeginFrame(void)
{
    ::ImGui::BeginFrame();
}

CIMGUI_API void cimgui::ImGuizmo_SetImGuiContext(ImGuiContext* ctx)
{
    ::ImGui::SetImGuiContext(ctx);
}

CIMGUI_API bool cimgui::ImGuizmo_IsOver(void)
{
    return ::ImGui::IsOver();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsing(void)
{
    return ::ImGui::IsUsing();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsingViewManipulate(void)
{
    return ::ImGui::IsUsingViewManipulate();
}

CIMGUI_API bool cimgui::ImGuizmo_IsViewManipulateHovered(void)
{
    return ::ImGui::IsViewManipulateHovered();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsingAny(void)
{
    return ::ImGui::IsUsingAny();
}

CIMGUI_API void cimgui::ImGuizmo_Enable(bool enable)
{
    ::ImGui::Enable(enable);
}

CIMGUI_API void cimgui::ImGuizmo_DecomposeMatrixToComponents(const float* matrix, float* translation, float* rotation, float* scale)
{
    ::ImGui::DecomposeMatrixToComponents(matrix, translation, rotation, scale);
}

CIMGUI_API void cimgui::ImGuizmo_RecomposeMatrixFromComponents(const float* translation, const float* rotation, const float* scale, float* matrix)
{
    ::ImGui::RecomposeMatrixFromComponents(translation, rotation, scale, matrix);
}

CIMGUI_API void cimgui::ImGuizmo_SetRect(float x, float y, float width, float height)
{
    ::ImGui::SetRect(x, y, width, height);
}

CIMGUI_API void cimgui::ImGuizmo_SetOrthographic(bool isOrthographic)
{
    ::ImGui::SetOrthographic(isOrthographic);
}

CIMGUI_API void cimgui::ImGuizmo_DrawAxes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGui::DrawAxes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmo_DrawCubes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGui::DrawCubes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGrid(const float* view, const float* projection, const float* matrix, const float gridSize)
{
    ::ImGui::DrawGrid(view, projection, matrix, gridSize);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGridCustom(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision)
{
    ::ImGui::DrawGridCustom(view, projection, matrix, gridSize, majorStep, subdivision);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGridCustomColor(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision, const ImU32 majorCol, const ImU32 minorCol, const ImU32 centerCol)
{
    ::ImGui::DrawGridCustomColor(view, projection, matrix, gridSize, majorStep, subdivision, majorCol, minorCol, centerCol);
}

CIMGUI_API bool cimgui::ImGuizmo_Manipulate(const float* view, const float* projection, ImGuizmo_OPERATION operation, ImGuizmo_MODE mode, float* matrix)
{
    return ::ImGui::Manipulate(view, projection, operation, mode, matrix);
}

CIMGUI_API bool cimgui::ImGuizmo_ManipulateEx(const float* view, const float* projection, ImGuizmo_OPERATION operation, ImGuizmo_MODE mode, float* matrix, float* deltaMatrix, const float* snap, const float* localBounds, const float* boundsSnap)
{
    return ::ImGui::Manipulate(view, projection, operation, mode, matrix, deltaMatrix, snap, localBounds, boundsSnap);
}

CIMGUI_API void cimgui::ImGuizmo_ViewManipulate(float* view, float length, ImVec2 position, ImVec2 size, ImU32 backgroundColor)
{
    ::ImGui::ViewManipulate(view, length, position, size, backgroundColor);
}

CIMGUI_API void cimgui::ImGuizmo_ViewManipulateFloatPtr(float* view, const float* projection, ImGuizmo_OPERATION operation, ImGuizmo_MODE mode, float* matrix, float length, ImVec2 position, ImVec2 size, ImU32 backgroundColor)
{
    ::ImGui::ViewManipulate(view, projection, operation, mode, matrix, length, position, size, backgroundColor);
}

CIMGUI_API void cimgui::ImGuizmo_SetAlternativeWindow(cimgui::ImGuiWindow* window)
{
    ::ImGui::SetAlternativeWindow(reinterpret_cast<::ImGuiWindow*>(window));
}

CIMGUI_API void    cimgui::ImGuizmo_PushID(const char* str_id)
{
    ::ImGui::PushID(str_id);
}

CIMGUI_API void    cimgui::ImGuizmo_PushIDStr(const char* str_id_begin, const char* str_id_end)
{
    ::ImGui::PushID(str_id_begin, str_id_end);
}

CIMGUI_API void    cimgui::ImGuizmo_PushIDPtr(const void* ptr_id)
{
    ::ImGui::PushID(ptr_id);
}

CIMGUI_API void    cimgui::ImGuizmo_PushIDInt(int int_id)
{
    ::ImGui::PushID(int_id);
}

CIMGUI_API void    cimgui::ImGuizmo_PopID(void)
{
    ::ImGui::PopID();
}

CIMGUI_API ImGuiID cimgui::ImGuizmo_GetID(const char* str_id)
{
    return ::ImGui::GetID(str_id);
}

CIMGUI_API ImGuiID cimgui::ImGuizmo_GetIDStr(const char* str_id_begin, const char* str_id_end)
{
    return ::ImGui::GetID(str_id_begin, str_id_end);
}

CIMGUI_API ImGuiID cimgui::ImGuizmo_GetIDPtr(const void* ptr_id)
{
    return ::ImGui::GetID(ptr_id);
}

CIMGUI_API bool cimgui::ImGuizmo_IsOverImGuizmo_OPERATION(ImGuizmo_OPERATION op)
{
    return ::ImGui::IsOver(op);
}

CIMGUI_API void cimgui::ImGuizmo_SetGizmoSizeClipSpace(float value)
{
    ::ImGui::SetGizmoSizeClipSpace(value);
}

CIMGUI_API ImGuizmo_MOVETYPE cimgui::ImGuizmo_GetActiveHandleType(void)
{
    return ::ImGui::GetActiveHandleType();
}

CIMGUI_API ImGuizmo_MOVETYPE cimgui::ImGuizmo_GetHoveredHandleType(void)
{
    return ::ImGui::GetHoveredHandleType();
}

CIMGUI_API ImGuizmo_MOVETYPE cimgui::ImGuizmo_GetActiveMoveType(void)
{
    return ::ImGui::GetActiveMoveType();
}

CIMGUI_API ImGuizmo_MOVETYPE cimgui::ImGuizmo_GetHoveredMoveType(void)
{
    return ::ImGui::GetHoveredMoveType();
}

CIMGUI_API void cimgui::ImGuizmo_AllowAxisFlip(bool value)
{
    ::ImGui::AllowAxisFlip(value);
}

CIMGUI_API void cimgui::ImGuizmo_SetAxisLimit(float value)
{
    ::ImGui::SetAxisLimit(value);
}

CIMGUI_API void cimgui::ImGuizmo_SetAxisMask(bool x, bool y, bool z)
{
    ::ImGui::SetAxisMask(x, y, z);
}

CIMGUI_API void cimgui::ImGuizmo_SetPlaneLimit(float value)
{
    ::ImGui::SetPlaneLimit(value);
}

CIMGUI_API bool cimgui::ImGuizmo_IsOverFloatPtr(float* position, float pixelRadius)
{
    return ::ImGui::IsOver(position, pixelRadius);
}

CIMGUI_API cimgui::ImGuizmo_Style* cimgui::ImGuizmo_GetStyle(void)
{
    return reinterpret_cast<::cimgui::ImGuizmo_Style*>(&::ImGui::GetStyle());
}
