// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#include "imgui.h"
#include "ImGuizmo.h"

#include <stdio.h>

typedef ImGuizmo::OPERATION OPERATION;
typedef ImGuizmo::MODE MODE;
typedef ImGuizmo::MOVETYPE MOVETYPE;
typedef ImGuizmo::COLOR COLOR;
typedef ImGuizmo::Style Style;

// Wrap this in a namespace to keep it separate from the C++ API.
#define DEAR_BINDINGS_INTERNAL_GLUE_CODE
namespace cimgui
{
    typedef ::OPERATION OPERATION;
    typedef ::MODE MODE;
    typedef ::MOVETYPE MOVETYPE;
    typedef ::COLOR COLOR;
    typedef ::Style Style;

    #include "cimguizmo.h"
}
#undef DEAR_BINDINGS_INTERNAL_GLUE_CODE
// By-value struct conversions

// Function stubs

#if 0

CIMGUI_API void cimgui::cEditTransform(Camera camera, matrix_t* matrix)
{
    ::EditTransform(reinterpret_cast<const ::Camera&>(camera), *matrix);
}

#endif // #if 0

CIMGUI_API void cimgui::ImGuizmo_SetDrawlist(void)
{
    ::ImGui::SetDrawlist();
}

CIMGUI_API void cimgui::ImGuizmo_SetDrawlistEx(ImDrawList* drawlist)
{
    ::ImGui::SetDrawlist(drawlist);
}

CIMGUI_API void cimgui::ImGuizmo_BeginFrame(void)
{
    ::ImGui::BeginFrame();
}

CIMGUI_API void cimgui::ImGuizmo_SetImGuiContext(ImGuiContext* ctx)
{
    ::ImGui::SetImGuiContext(ctx);
}

CIMGUI_API bool cimgui::ImGuizmo_IsOver(void)
{
    return ::ImGui::IsOver();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsing(void)
{
    return ::ImGui::IsUsing();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsingViewManipulate(void)
{
    return ::ImGui::IsUsingViewManipulate();
}

CIMGUI_API bool cimgui::ImGuizmo_IsViewManipulateHovered(void)
{
    return ::ImGui::IsViewManipulateHovered();
}

CIMGUI_API bool cimgui::ImGuizmo_IsUsingAny(void)
{
    return ::ImGui::IsUsingAny();
}

CIMGUI_API void cimgui::ImGuizmo_Enable(bool enable)
{
    ::ImGui::Enable(enable);
}

CIMGUI_API void cimgui::ImGuizmo_DecomposeMatrixToComponents(const float* matrix, float* translation, float* rotation, float* scale)
{
    ::ImGui::DecomposeMatrixToComponents(matrix, translation, rotation, scale);
}

CIMGUI_API void cimgui::ImGuizmo_RecomposeMatrixFromComponents(const float* translation, const float* rotation, const float* scale, float* matrix)
{
    ::ImGui::RecomposeMatrixFromComponents(translation, rotation, scale, matrix);
}

CIMGUI_API void cimgui::ImGuizmo_SetRect(float x, float y, float width, float height)
{
    ::ImGui::SetRect(x, y, width, height);
}

CIMGUI_API void cimgui::ImGuizmo_SetOrthographic(bool isOrthographic)
{
    ::ImGui::SetOrthographic(isOrthographic);
}

CIMGUI_API void cimgui::ImGuizmo_DrawAxes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGui::DrawAxes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmo_DrawCubes(const float* view, const float* projection, const float* matrices, int matrixCount)
{
    ::ImGui::DrawCubes(view, projection, matrices, matrixCount);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGrid(const float* view, const float* projection, const float* matrix, const float gridSize)
{
    ::ImGui::DrawGrid(view, projection, matrix, gridSize);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGridCustom(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision)
{
    ::ImGui::DrawGridCustom(view, projection, matrix, gridSize, majorStep, subdivision);
}

CIMGUI_API void cimgui::ImGuizmo_DrawGridCustomColor(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision, const ImU32 majorCol, const ImU32 minorCol, const ImU32 centerCol)
{
    ::ImGui::DrawGridCustomColor(view, projection, matrix, gridSize, majorStep, subdivision, majorCol, minorCol, centerCol);
}
