// THIS FILE HAS BEEN AUTO-GENERATED BY THE 'DEAR BINDINGS' GENERATOR.
// **DO NOT EDIT DIRECTLY**
// https://github.com/dearimgui/dear_bindings

#ifdef DEAR_BINDINGS_INTERNAL_GLUE_CODE
#include "imgui.h"
#else
#include "dcimgui.h"
#endif
// https://github.com/CedricGuillemet/ImGuizmo
// v1.92.5 WIP
//
// The MIT License(MIT)
//
// Copyright(c) 2016-2026 Cedric Guillemet and contributors
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files(the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and / or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions :
//
// The above copyright notice and this permission notice shall be included in all
// copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
// SOFTWARE.
//
// -------------------------------------------------------------------------------------------
// History :
// 2026/05/03 v1.9 release. CMake build system, vcpkg support, many fixes and new features from contributors.
// 2019/11/03 View gizmo
// 2016/09/11 Behind camera culling. Scaling Delta matrix not multiplied by source matrix scales. local/world rotation and translation fixed. Display message is incorrect (X: ... Y:...) in local mode.
// 2016/09/09 Hatched negative axis. Snapping. Documentation update.
// 2016/09/04 Axis switch and translation plan autohiding. Scale transform stability improved
// 2016/09/01 Mogwai changed to Manipulate. Draw debug cube. Fixed inverted scale. Mixing scale and translation/rotation gives bad results.
// 2016/08/31 First version
//
// -------------------------------------------------------------------------------------------
// Future (no order):
//
// - Multi view
// - display rotation/translation/scale infos in local/world space and not only local
// - finish local/world matrix application
// - OPERATION as bitmask
//
// -------------------------------------------------------------------------------------------
// Example
#if 0
CIMGUI_API void cEditTransform(Camera camera, matrix_t* matrix);
#endif // #if 0
#pragma once

#ifdef __cplusplus
extern "C"
{
#endif
#ifdef USE_IMGUI_API
#include "imconfig.h"
#endif // #ifdef USE_IMGUI_API
#ifndef CIMGUI_API
#define CIMGUI_API
#endif // #ifndef CIMGUI_API
#ifndef ImGui
#define ImGui ImGuizmo
#endif // #ifndef ImGui
typedef struct ImGuiWindow_t ImGuiWindow;

// call inside your own window and before Manipulate() in order to draw gizmo to that window.
// Or pass a specific ImDrawList to draw to (e.g. GetForegroundDrawList()).
CIMGUI_API void ImGuizmo_SetDrawlist(void);                                 // Implied drawlist = nullptr
CIMGUI_API void ImGuizmo_SetDrawlistEx(ImDrawList* drawlist /* = nullptr */);

// call BeginFrame right after ImGui_XXXX_NewFrame();
CIMGUI_API void ImGuizmo_BeginFrame(void);

// this is necessary because when imguizmo is compiled into a dll, and imgui into another
// globals are not shared between them.
// More details at https://stackoverflow.com/questions/19373061/what-happens-to-global-and-static-variables-in-a-shared-library-when-it-is-dynam
// expose method to set imgui context
CIMGUI_API void ImGuizmo_SetImGuiContext(ImGuiContext* ctx);

// return true if mouse cursor is over any gizmo control (axis, plan or screen component)
CIMGUI_API bool ImGuizmo_IsOver(void);

// return true if mouse IsOver or if the gizmo is in moving state
CIMGUI_API bool ImGuizmo_IsUsing(void);

// return true if the view gizmo is in moving state
CIMGUI_API bool ImGuizmo_IsUsingViewManipulate(void);
// only check if your mouse is over the view manipulator - no matter whether it's active or not
CIMGUI_API bool ImGuizmo_IsViewManipulateHovered(void);

// return true if any gizmo is in moving state
CIMGUI_API bool ImGuizmo_IsUsingAny(void);

// enable/disable the gizmo. Stay in the state until next call to Enable.
// gizmo is rendered with gray half transparent color when disabled
CIMGUI_API void ImGuizmo_Enable(bool enable);

// helper functions for manualy editing translation/rotation/scale with an input float
// translation, rotation and scale float points to 3 floats each
// Angles are in degrees (more suitable for human editing)
// example:
// float matrixTranslation[3], matrixRotation[3], matrixScale[3];
// DecomposeMatrixToComponents(gizmoMatrix.m16, matrixTranslation, matrixRotation, matrixScale);
// InputFloat3("Tr", matrixTranslation, 3);
// InputFloat3("Rt", matrixRotation, 3);
// InputFloat3("Sc", matrixScale, 3);
// RecomposeMatrixFromComponents(matrixTranslation, matrixRotation, matrixScale, gizmoMatrix.m16);
//
// These functions have some numerical stability issues for now. Use with caution.
CIMGUI_API void ImGuizmo_DecomposeMatrixToComponents(const float* matrix, float* translation, float* rotation, float* scale);
CIMGUI_API void ImGuizmo_RecomposeMatrixFromComponents(const float* translation, const float* rotation, const float* scale, float* matrix);

CIMGUI_API void ImGuizmo_SetRect(float x, float y, float width, float height);
// default is false
CIMGUI_API void ImGuizmo_SetOrthographic(bool isOrthographic);

// Render coordinate system axes (red X, green Y and blue Z). Usefull for debug/tests
CIMGUI_API void ImGuizmo_DrawAxes(const float* view, const float* projection, const float* matrices, int matrixCount);
// Render a cube with face color corresponding to face normal. Usefull for debug/tests
CIMGUI_API void ImGuizmo_DrawCubes(const float* view, const float* projection, const float* matrices, int matrixCount);
CIMGUI_API void ImGuizmo_DrawGrid(const float* view, const float* projection, const float* matrix, const float gridSize);
// Render grid with customizable major line step and amount of segments between major lines.
// NOTE(m.wlasiuk) : calling this function with majorStep = 1.0f and subdivision = 1 is equivalent to DrawGrid in terms of the end result but performs more calculations
CIMGUI_API void ImGuizmo_DrawGridCustom(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision);
// Render grid with customizable major line step and amount of segments between major lines and with possibility to set custom colors for major, minor and center lines
CIMGUI_API void ImGuizmo_DrawGridCustomColor(const float* view, const float* projection, const float* matrix, const float gridSize, const float majorStep, const unsigned int subdivision, const ImU32 majorCol, const ImU32 minorCol, const ImU32 centerCol);

// call it when you want a gizmo
// Needs view and projection matrices.
// matrix parameter is the source matrix (where will be gizmo be drawn) and might be transformed by the function. Return deltaMatrix is optional
// translation is applied in world space
#ifdef __cplusplus
} // End of extern "C" block
#endif
